
spring:
  cloud:
    gateway:
      routes:
        - id:  route_1
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
        - id:  route_2
          uri: lb://produit-service
          predicates:
            - Path=/produits/**
